name: 'Remove merged branches'
description: 'Remove merged branches without PR as a trigger.'
branding:
  icon: 'chevron-down'
  color: 'white'
inputs:
  protected_branch:
    description: 'Protected branch'
    required: false
    default: 'main'
  head_branch:
    description: 'Head branch'
    default: ${{ github.ref }}
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.event_before }}
    - ${{ inputs.protected_branch }}
